global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'go-app-instances'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['go-app-1:8080', 'go-app-2:8080']
    scrape_timeout: 10s

  - job_name: 'postgres'
    scrape_interval: 30s
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_timeout: 15s